### ISSUE TITLE
Array of items (open api 2)

### ISSUE THREAD

**Issue by grochol** [bart-sk/swagger-js-codegen#15]
swagger.yaml

```
status_log:
  type: array
  items:
    type: object
    properties:
      ips:
        type: [array, "null"]
        items:
          type: [string, "null"]
```

Expected behaviour:

```
status_log?: Array<{
    ips?: string[] | null;
}>;
```

Bug behaviour:

```
status_log?: Array<{
    ips?: array | null;
}>;
```
